version: '3'
services:
  config-service:
    image: config-server
    ports:
      - "8888:8888"
  eureka-server:
    image: discovery
    ports:
      - "8761:8761"
  gateway-service:
    image: gateway
    ports:
      - "8222:8222"
  mysql-database:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=authors
  mysql-books:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=books
  books-service:
    image: books
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
    depends_on:
      - mysql-books
  authors-service:
    image: authors
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=development
    depends_on:
      - mysql-database



