eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

spring:
  application:
    name: books
  datasource:
    url: jdbc:mysql://localhost:3306/books
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  management:
    tracing:
      sampling:
        probability: 1.0