eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: books
          uri: http://localhost:8080
          predicates:
            - Path=/books/**
        - id: authors
          uri: http://localhost:8081
          predicates:
            - Path=/authors/**
management:
  tracing:
    sampling:
      probability: 1.0            -